<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.20348.0</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <AssemblyName>AutoPingCsharpNet</AssemblyName>
    <RootNamespace>AutoPingCsharp_Net</RootNamespace>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <SupportedOSPlatformVersion>8.0</SupportedOSPlatformVersion>
    <AssemblyTitle>Auto Ping Worker</AssemblyTitle>
    <StartupObject>AutoPingCsharp_Net.App</StartupObject>
    <ApplicationIcon>Resources\MainIcon.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <Resource Include="Resources\MainIcon.ico">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>
</Project>