<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>AutoPingTestNet</AssemblyName>
    <RootNamespace>AutoPingTest_Net</RootNamespace>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AssemblyTitle>Auto Ping Console</AssemblyTitle>
    <PublishTrimmed>True</PublishTrimmed>
    <PublishAot>True</PublishAot>
  </PropertyGroup>
</Project>